# Base image
FROM node:16

# Make folder to put our files in
RUN mkdir -p /usrer/src/app
RUN mkdir -p /usr/src/app/client

# Set working directory so that all
# subsequent command runs in this folder
WORKDIR /user/src/app/client


# Copy package json and install dependencies
COPY package*.json ./
RUN npm install

# Copy our app

COPY . .
# Expose port to access server
EXPOSE 5173

# Command to run our app
CMD [ "npm", "run", "dev" ]