# Base image
FROM node:16

# Make folder to put our files in

RUN mkdir -p /user/src/app
RUN mkdir -p /user/src/app/server

# Set working directory so that all subsequent command runs in this folder.
WORKDIR /user/src/app/server

#Copy package.json and install dependencies

COPY package*.json ./
RUN npm install

# Copy our app

COPY . .

#Expose port to access server.
EXPOSE 3333

#Command to run our app

CMD ["npm", "start"]